version: '3'
services:
  serviceaccessgui:
    image: riccardoob/serviceaccessgui:latest
    ports:
      - 8075:8075
#    networks:
#      - shared
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    command: [ "bash", "./unibo.serviceaccessGUI" ]
  servicestatusgui:
    image: riccardoob/servicestatusgui:latest
    ports:
      - 8065:8065
#    networks:
#      - shared
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  coldstorageservice:
    image: riccardoob/coldstorageservice23:latest
    ports:
#      - 8020:8020
      - 8021:8021
#    networks:
#      - shared
  wenv:
    image: riccardoob/virtualrobotdisi23:1.0
    ports:
      - 8090:8090
      - 8091:8091
#    networks:
#      - shared
  basicrobot23:
    image: riccardoob/basicrobot23:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
#    networks:
#      - shared
networks:
  shared:
    driver: bridge
    
