version: '3'
services:
  wenv:
    image: virtualrobotdisi23:1.0
    ports:
      - 8090:8090
      - 8091:8091
  basicrobot23:
    image: basicrobot23:2.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp

## -------------------------------------------------------------
## TODO See https://docs.docker.com/compose/startup-order/
## -------------------------------------------------------------
## docker-compose -f basicrobot23.yaml  up
## docker-compose run --service-ports wenv
## docker-compose run --service-ports vrobotclient  ATTIVA ANCHE wenv
